// apps/playground-vue-arco/src/views/TableDemo.vue
<template>
    <div class="table-demo">
        <h3 style="margin-top: 0; margin-bottom: 24px;">ProTable 综合渲染压测 & 列配置演示</h3>
        
        <a-alert type="info" style="margin-bottom: 16px;">
            <template #title>列配置功能说明</template>
            <div style="font-size: 12px; line-height: 1.6;">
                点击表格右上角的「列设置」按钮，可以勾选/取消列的显隐。配置会自动保存到浏览器 localStorage，刷新页面会自动恢复。
            </div>
        </a-alert>
        
        <!-- 核心 ProTable 组件展示区：增加 cacheKey 和 showSetting 开启列配置功能 -->
        <ProTable 
            :columns="columns" 
            :requestApi="fetchMockData"
            cacheKey="playground-table-demo"
            :showSetting="true"
        />
    </div>
</template>

<script setup lang="ts">
import { ProTable } from 'rongshiyi-ui-vue-arco';
import type { ProColumnData } from 'rongshiyi-ui-vue-arco';

// ==========================================
// 1. 定义表盘列基础数据配置
// ==========================================
const columns: ProColumnData[] = [
    {
        title: '员工姓名',
        dataIndex: 'name',
        width: 150,
        search: true, // 开启上层表单搜索
        valueType: 'input',
        tooltip: '员工的真实花名或姓名',
        copyable: true
    },
    {
        title: '头像照片',
        dataIndex: 'avatar',
        width: 120,
        valueType: 'image'
    },
    {
        title: '个人简介',
        dataIndex: 'bio',
        width: 150,
        valueType: 'html',
        tooltip: '由富文本编辑器生成的 HTML 代码'
    },
    {
        title: '技术栈',
        dataIndex: 'skills',
        width: 180,
        valueType: 'array',
        tooltip: '数组格式的数据，自动转换为逗号分隔'
    },
    {
        title: '博客链接',
        dataIndex: 'blogUrl',
        width: 120,
        valueType: 'link',
        copyable: true
    },
    {
        title: '当前状态',
        dataIndex: 'status',
        width: 100,
        search: true, // 开启过滤
        valueType: 'select',
        options: [
            { label: '在职', value: 'active' },
            { label: '离职', value: 'dimission' }
        ]
    },
    {
        title: '系统账号',
        dataIndex: 'accountEnabled',
        width: 100,
        valueType: 'switch',
        switchConfig: {
            activeText: '启用',
            inactiveText: '封禁',
            onChange: (val: any, row: any) => console.log('修改账号状态:', val, row.name)
        }
    },
    {
        title: '入职时间',
        dataIndex: 'entryDate',
        width: 150,
        search: true,
        valueType: 'date',
        dateFormat: 'YYYY/MM/DD'
    },
    {
        title: '操作',
        dataIndex: 'action',
        width: 180,
        align: 'center',
        fixed: 'right',
        valueType: 'operation',
        operation: [
            {
                label: '查看',
                icon: 'icon-eye',
                onClick: (row: any) => console.log('查看:', row.name)
            },
            {
                label: '编辑',
                icon: 'icon-edit',
                onClick: (row: any) => console.log('编辑:', row.name)
            },
            {
                label: '封号',
                icon: 'icon-stop',
                disabled: (row: any) => !row.accountEnabled,
                onClick: (row: any) => console.log('封号:', row.name)
            },
            {
                label: '删除',
                icon: 'icon-delete',
                onClick: (row: any) => console.log('删除:', row.name)
            }
        ]
    }
];

// ==========================================
// 2. 编写模拟数据与网络请求 API
// ==========================================
/**
 * 模拟的网络请求延时并返回数据
 * 目的是压测 ProTable 的 loading 和翻页响应能力
 */
const fetchMockData = async (params: any) => {
    console.log('ProTable 触发查询，提交参数为：', params);

    // 主动挂挂载 1 秒延时，肉眼观察组件自身封装的 Loading 动画拦截是否生效
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // 构造并返回 5 条前端写死的范例数据
    const mockTableData = Array.from({ length: 5 }).map((_, idx) => ({
        id: idx + 1 + (params.page - 1) * params.pageSize,
        name: `架构体验官 ${idx + 1}`,
        avatar: 'https://p1-arco.byteimg.com/tos-cn-i-uwbnlip3yd/a8c8cdb109cb051163646151a4a5083b.png~tplv-uwbnlip3yd-webp.webp',
        bio: '<span style="color: blue">追求极致体验</span>',
        skills: ['Vue3', 'React', 'Node.js', 'Rust'],
        blogUrl: 'https://liujinrong.cn',
        status: idx % 3 === 0 ? 'dimission' : 'active',
        accountEnabled: idx % 2 === 0,
        entryDate: `2026-03-0${(idx % 9) + 1}`,
    }));

    // 需要解构一层返回结构适配组件约定的响应外壳 { data, total }
    return {
        data: mockTableData,
        total: 36 // 模拟具有分页的情况
    };
};
</script>

// apps/playground-react/src/demos/TableDemo.tsx
import { Button, message, Tag } from 'antd';
import { ProTable } from 'rongshiyi-ui-react';
import type { ProColumnType } from 'rongshiyi-ui-react';

interface UserItem {
    id: string;
    name: string;
    age: number;
    role: number;
    status: boolean;
    joinDate: string;
    avatar: string;
}

const mockData: UserItem[] = Array.from({ length: 55 }).map((_, idx) => ({
    id: `USR-${1000 + idx}`,
    name: `测试员工 ${idx + 1}`,
    age: 20 + (idx % 30),
    role: idx % 3,
    status: idx % 4 !== 0,
    joinDate: new Date(Date.now() - idx * 86400000 * 5).toISOString(),
    avatar: `https://i.pravatar.cc/150?img=${idx + 1}`,
}));

const mockRequest = async (params: Record<string, any>) => {
    return new Promise<{ data: UserItem[]; total: number; success: boolean }>((resolve) => {
        setTimeout(() => {
            let filteredData = [...mockData];
            if (params.name) {
                filteredData = filteredData.filter((item) => item.name.includes(params.name));
            }
            if (params.role !== undefined) {
                filteredData = filteredData.filter((item) => item.role === params.role);
            }

            const current = params.current || 1;
            const pageSize = params.pageSize || 10;
            const start = (current - 1) * pageSize;
            const end = start + pageSize;

            resolve({
                data: filteredData.slice(start, end),
                total: filteredData.length,
                success: true,
            });
        }, 500);
    });
};

const columns: ProColumnType<UserItem>[] = [
    {
        title: '员工编号',
        dataIndex: 'id',
        width: 120,
        search: true,
        copyable: true,
        tooltip: '系统唯一识别码',
    },
    {
        title: '头像',
        dataIndex: 'avatar',
        valueType: 'image',
    },
    {
        title: '姓名',
        dataIndex: 'name',
        search: true,
    },
    {
        title: '年龄',
        dataIndex: 'age',
        width: 80,
        align: 'center',
        hideInTable: true,
    },
    {
        title: '角色',
        dataIndex: 'role',
        valueType: 'select',
        search: true,
        options: [
            { label: '管理员', value: 0 },
            { label: '普通员工', value: 1 },
            { label: '实习生', value: 2 },
        ],
        render: (_: any, record: UserItem) => {
            const colors = ['red', 'green', 'blue'];
            const labels = ['管理员', '普通员工', '实习生'];
            return <Tag color={colors[record.role]}>{labels[record.role]}</Tag>;
        },
    },
    {
        title: '账号状态',
        dataIndex: 'status',
        valueType: 'switch',
        switchConfig: {
            activeText: '正常',
            inactiveText: '冻结',
            onChange: (val: any, row: UserItem) => message.success(`切换 ${row.name} 状态至 ${val ? '正常' : '冻结'}`),
        },
    },
    {
        title: '入职日期',
        dataIndex: 'joinDate',
        valueType: 'date',
        dateFormat: 'YYYY/MM/DD',
        search: true,
    },
    {
        title: '操作',
        key: 'action',
        width: 200,
        valueType: 'operation',
        operation: [
            { label: '编辑', onClick: (r: UserItem) => message.info(`编辑: ${r.name}`) },
            { label: '授权', disabled: (r: UserItem) => !r.status, onClick: (r: UserItem) => message.info(`授权: ${r.name}`) },
            { label: '删除', onClick: (r: UserItem) => message.error(`删除: ${r.name} - ${r.id}`) },
        ],
    },
];

export default function TableDemo() {
    return (
        <ProTable<UserItem>
            cacheKey="demo-user-list-table"
            rowKey="id"
            requestApi={mockRequest}
            columns={columns}
            toolBarRender={() => [
                <Button key="add" type="primary" onClick={() => message.success('新建表单触发')}>
                    新建员工
                </Button>,
                <Button key="export" onClick={() => message.info('正在导出...')}>
                    导出
                </Button>,
            ]}
        />
    );
}
