// packages/ui-vue/src/components/ProTable/index.vue
<template>
    <div class="rongshiyi-pro-table">
        <!-- 工具栏：列设置按钮 -->
        <div class="pro-table-toolbar" v-if="props.showSetting !== false">
            <a-popover placement="bottom" :width="280">
                <a-button type="outline" size="small">
                    <template #icon><icon-settings /></template>
                    列设置
                </a-button>

                <template #content>
                    <div class="pro-table-setting-panel">
                        <!-- 列表 -->
                        <div class="setting-content" v-if="currentColumns.length > 0">
                            <a-checkbox-group
                                :model-value="currentColumns.filter(c => c.visible !== false).map(c => c.dataIndex)"
                                @update:model-value="handleColumnVisibilityChange"
                            >
                                <a-checkbox v-for="col in currentColumns" :key="col.dataIndex" :value="col.dataIndex">
                                    {{ col.title }}
                                </a-checkbox>
                            </a-checkbox-group>
                        </div>

                        <a-empty v-else description="暂无可配置列" />

                        <!-- 分割线 -->
                        <a-divider style="margin: 8px 0;" v-if="currentColumns.length > 0" />

                        <!-- 重置按钮 -->
                        <div class="setting-actions" v-if="currentColumns.length > 0">
                            <a-button type="text" size="small" @click="resetColumnsToDefault">
                                重置默认
                            </a-button>
                        </div>
                    </div>
                </template>
            </a-popover>
        </div>

        <!-- 顶部搜索表单区域 -->
        <div class="pro-table-search" v-if="searchColumns.length > 0">
            <a-form :model="searchModel" layout="horizontal" auto-label-width @submit="handleSearch">
                <a-grid :cols="{ xs: 1, sm: 2, md: 3, lg: 4, xl: 4 }" :col-gap="10" :row-gap="10">
                    <a-grid-item v-for="col in searchColumns" :key="col.dataIndex">
                        <a-form-item :field="col.dataIndex" :label="col.title">

                            <!-- 动态渲染不同类型的输入控件 -->
                            <template v-if="col.valueType === 'select'">
                                <a-select v-model="searchModel[col.dataIndex as string]" :options="col.options"
                                    placeholder="请选择" allow-clear />
                            </template>

                            <template v-else-if="col.valueType === 'date'">
                                <a-date-picker v-model="searchModel[col.dataIndex as string]" style="width: 100%"
                                    allow-clear />
                            </template>

                            <!-- 默认降级为普通输入框 -->
                            <template v-else>
                                <a-input v-model="searchModel[col.dataIndex as string]" placeholder="请输入" allow-clear />
                            </template>

                        </a-form-item>
                    </a-grid-item>

                    <!-- 搜索操作按钮组 -->
                    <a-grid-item class="search-actions">
                        <a-space>
                            <a-button type="primary" html-type="submit">查询</a-button>
                            <a-button @click="handleReset">重置</a-button>
                        </a-space>
                    </a-grid-item>
                </a-grid>
            </a-form>
        </div>

        <!-- 底部数据表格展示区域 -->
        <div class="pro-table-content">
            <a-table :data="tableData" :loading="loading" :pagination="pagination" :scroll="computedScroll"
                @page-change="handlePageChange" @page-size-change="handlePageSizeChange">

                <template #columns>
                    <a-table-column v-for="col in displayColumns" :key="col.dataIndex" :title="col.title"
                        :data-index="col.dataIndex" :width="col.width" :align="col.align" :fixed="col.fixed">

                        <!-- 拦截表头插槽：实现 tooltip 增强 -->
                        <template #title>
                            <span>{{ col.title }}</span>
                            <a-tooltip v-if="(col as ProColumnData).tooltip" :content="(col as ProColumnData).tooltip">
                                <icon-question-circle
                                    style="margin-left: 4px; color: var(--color-text-3); cursor: pointer;" />
                            </a-tooltip>
                        </template>

                        <!-- 拦截数据单元格插槽 -->
                        <template #cell="{ record, rowIndex }">
                            <!-- 1. 首先检查是否有外部重写该列的插槽 (业务层传进来的 #slotName) -->
                            <slot v-if="col.slotName && $slots[col.slotName as string]" :name="col.slotName"
                                :column="col" :record="record" :rowIndex="rowIndex">
                            </slot>

                            <!-- 2. 如果没有被重写，执行内部智能映射逻辑 -->
                            <template v-else>
                                <!-- valueType === 'slot' -->
                                <template v-if="col.valueType === 'slot'">
                                    <slot :name="col.componentSlot || col.slotName" :record="record" :column="col"
                                        :rowIndex="rowIndex" />
                                </template>

                                <!-- valueType === 'image' -->
                                <template v-else-if="col.valueType === 'image'">
                                    <a-image v-if="record[col.dataIndex || '']" :src="record[col.dataIndex || '']"
                                        height="40" preview />
                                    <span v-else style="color: var(--color-text-4)">暂无图片</span>
                                </template>

                                <!-- valueType === 'video' -->
                                <template v-else-if="col.valueType === 'video'">
                                    <video v-if="record[col.dataIndex || '']" :src="record[col.dataIndex || '']"
                                        height="40" controls />
                                    <span v-else style="color: var(--color-text-4)">暂无视频</span>
                                </template>

                                <!-- valueType === 'html' -->
                                <template v-else-if="col.valueType === 'html'">
                                    <span v-html="record[col.dataIndex || '']"></span>
                                </template>

                                <!-- valueType === 'date' -->
                                <template v-else-if="col.valueType === 'date'">
                                    {{ formatDate(record[col.dataIndex || ''], col.dateFormat) }}
                                </template>

                                <!-- valueType === 'switch' -->
                                <template v-else-if="col.valueType === 'switch'">
                                    <a-switch v-model="record[col.dataIndex || '']"
                                        :checked-text="col.switchConfig?.activeText"
                                        :unchecked-text="col.switchConfig?.inactiveText"
                                        :checked-value="col.switchConfig?.activeValue ?? true"
                                        :unchecked-value="col.switchConfig?.inactiveValue ?? false"
                                        :disabled="col.switchConfig?.disabled?.(record)"
                                        @change="(val: any) => col.switchConfig?.onChange?.(val, record)" />
                                </template>

                                <!-- valueType === 'enum' || 'select' -->
                                <template v-else-if="col.valueType === 'enum' || col.valueType === 'select'">
                                    {{ getEnumLabel(record[col.dataIndex || ''], col.options) }}
                                </template>

                                <!-- valueType === 'array' -->
                                <template v-else-if="col.valueType === 'array'">
                                    {{ formatArray(record[col.dataIndex || '']) }}
                                </template>

                                <!-- valueType === 'link' -->
                                <template v-else-if="col.valueType === 'link'">
                                    <a-link>{{ record[col.dataIndex || ''] }}</a-link>
                                </template>

                                <!-- valueType === 'operation' -->
                                <template v-else-if="col.valueType === 'operation'">
                                    <a-space>
                                        <template v-for="(btn, index) in getVisibleOperations(col.operation, record)"
                                            :key="index">
                                            <a-button type="text" size="small" :disabled="btn.disabled?.(record)"
                                                @click="btn.onClick(record)">
                                                <!-- 支持图标和文字 -->
                                                <template #icon v-if="btn.icon">
                                                    <component :is="btn.icon" />
                                                </template>
                                                {{ btn.label }}
                                            </a-button>
                                        </template>

                                        <a-dropdown v-if="getDropdownOperations(col.operation, record).length > 0">
                                            <a-button type="text" size="small">
                                                <template #icon><icon-more /></template>
                                            </a-button>
                                            <template #content>
                                                <a-doption
                                                    v-for="(btn, index) in getDropdownOperations(col.operation, record)"
                                                    :key="index" :disabled="btn.disabled?.(record)"
                                                    @click="btn.onClick(record)">
                                                    <template #icon v-if="btn.icon">
                                                        <component :is="btn.icon" />
                                                    </template>
                                                    {{ btn.label }}
                                                </a-doption>
                                            </template>
                                        </a-dropdown>
                                    </a-space>
                                </template>

                                <!-- 兜底：直接输出原值 -->
                                <template v-else>
                                    <span>{{ record[col.dataIndex || ''] }}</span>
                                    <!-- 一键复制增强 -->
                                    <a-tooltip v-if="col.copyable && record[col.dataIndex || '']" content="点击复制">
                                        <a-button type="text" size="mini"
                                            style="margin-left: 4px; padding: 0 4px; height: 20px;"
                                            @click="handleCopy(record[col.dataIndex || ''])">
                                            <template #icon><icon-copy /></template>
                                        </a-button>
                                    </a-tooltip>
                                </template>
                            </template>
                        </template>
                    </a-table-column>
                </template>

                <!-- 其他非列相关的插槽（如 empty 等）原样击穿给 a-table -->
                <template v-for="(_, slotName) in $slots" #[slotName]="slotProps" :key="slotName">
                    <!-- 过滤掉已手动处理的插槽 -->
                    <slot v-if="!displayColumns.find(c => c.slotName === slotName) && slotName !== 'th'" :name="slotName"
                        v-bind="slotProps || {}"></slot>
                </template>
            </a-table>
        </div>
    </div>
</template>

<script setup lang="ts">
import { ref, reactive, computed, onMounted } from 'vue';
import { Message } from '@arco-design/web-vue';
import { IconQuestionCircle, IconCopy, IconMore, IconSettings } from '@arco-design/web-vue/es/icon';
import dayjs from 'dayjs';
import type { ProTableProps, ProColumnData } from './types';

/**
 * 内部列配置扩展，增加 visible 标记
 */
interface ColumnWithVisibility extends ProColumnData {
    visible?: boolean;
}

// ==========================================
// 1. 属性定义与基础状态声明
// ==========================================
const props = defineProps<ProTableProps>();

const loading = ref(false);
const tableData = ref<any[]>([]);
const searchModel = reactive<Record<string, any>>({});

// 维护当前列的可见性状态（不直接修改原始 columns）
const currentColumns = ref<ColumnWithVisibility[]>([]);

const pagination = reactive({
    current: 1,
    pageSize: 10,
    total: 0,
    showTotal: true,
    showPageSize: true
});

// ==========================================
// 2. 派生状态计算 (Computed)
// ==========================================
// 过滤出所有标示为需要被搜索的列配置
const searchColumns = computed(() => {
    return props.columns.filter((col: ProColumnData) => col.search === true);
});

// 重构 columns 配置，强制让带有特殊渲染逻辑的列走自定义插槽代理
const tableColumnsWithSlotName = computed(() => {
    return currentColumns.value.map((col) => {
        // 如果列配置了特殊渲染配置，但却未申明 slotName，
        // 强制打上一个 slotName 标记，从而引导 a-table 将其交由内部捕获
        const needsCustomRender = col.valueType || col.copyable;
        if (needsCustomRender && !col.slotName) {
            return {
                ...col,
                slotName: col.dataIndex // 以 dataIndex 作为默认的插槽标识
            };
        }
        return col;
    });
});

// 计算过滤后的显示列（排除 visible=false 的列）
const displayColumns = computed(() => {
    return tableColumnsWithSlotName.value.filter(col => col.visible !== false) as ProColumnData[];
});

// 计算自适应的滚动维度配置：如果业务没传，但是配置有 fixed 列，则提供 max-content 给 Arco 以激活固定列机制
const computedScroll = computed(() => {
    if (props.scroll) {
        return props.scroll;
    }
    const hasFixed = props.columns.some(col => !!col.fixed);
    if (hasFixed) {
        return { x: 'max-content' };
    }
    return undefined;
});

// ==========================================
// 3. 核心工具与渲染辅助函数 (Helpers)
// ==========================================

/**
 * 格式化日期：支持单日期与数据范围
 */
const formatDate = (val: any, formatStr = 'YYYY-MM-DD') => {
    if (!val) return '-';
    if (Array.isArray(val) && val.length === 2) {
        return `${dayjs(val[0]).format(formatStr)} 到 ${dayjs(val[1]).format(formatStr)}`;
    }
    return dayjs(val).format(formatStr);
};

/**
 * 获取翻译字典标签
 */
const getEnumLabel = (val: any, options?: any[]) => {
    if (!options) return val;
    const hit = options.find(opt => opt.value === val);
    return hit ? hit.label : val;
};

/**
 * 格式化数组
 */
const formatArray = (val: any) => {
    if (Array.isArray(val)) {
        return val.join(', ');
    }
    return String(val);
};

/**
 * 获取外显操作按钮（最多截取前 2 个，如果总数超过 3 个）
 */
const getVisibleOperations = (operations?: any[], record?: any) => {
    if (!operations) return [];
    if (operations.length <= 3) return operations;
    return operations.slice(0, 2);
};

/**
 * 获取下拉隐藏的操作按钮，即超过 2 个后的所有按钮
 */
const getDropdownOperations = (operations?: any[], record?: any) => {
    if (!operations || operations.length <= 3) return [];
    return operations.slice(2);
};

/**
 * 处理一键复制到剪贴板
 */
const handleCopy = async (text: string) => {
    try {
        await navigator.clipboard.writeText(String(text));
        Message.success('复制成功');
    } catch (err) {
        Message.error('复制失败，请检查浏览器权限');
    }
};

// ==========================================
// 4. 核心交互函数集 (Actions)
// ==========================================

/**
 * 获取表格核心数据
 */
const fetchData = async () => {
    if (!props.requestApi) return;

    loading.value = true;
    try {
        // 组装查询参数：分页信息 + 表单条件
        const params = {
            page: pagination.current,
            pageSize: pagination.pageSize,
            ...searchModel
        };

        // 执行由外部注入的数据请求逻辑
        const { data, total } = await props.requestApi(params);
        tableData.value = data || [];
        pagination.total = total || 0;
    } catch (err) {
        console.error('ProTable 请求数据失败:', err);
    } finally {
        loading.value = false;
    }
};

/**
 * 触发查询
 */
const handleSearch = () => {
    pagination.current = 1; // 搜索时重置回第一页
    fetchData();
};

/**
 * 重置查询条件
 */
const handleReset = () => {
    // 清空 reactive 对象中的绑定值
    Object.keys(searchModel).forEach(key => {
        searchModel[key] = undefined;
    });
    handleSearch();
};

/**
 * 分页页码切换
 */
const handlePageChange = (page: number) => {
    pagination.current = page;
    fetchData();
};

/**
 * 每页展示条数切换
 */
const handlePageSizeChange = (pageSize: number) => {
    pagination.current = 1;
    pagination.pageSize = pageSize;
    fetchData();
};

// ==========================================
// 5. 列可见性持久化管理
// ==========================================

/**
 * 从 localStorage 读取该表格的列配置
 */
const loadColumnVisibilityFromCache = () => {
    if (!props.cacheKey) return null;

    try {
        const cacheKey = `PRO_TABLE_COLUMNS_${props.cacheKey}`;
        const cached = localStorage.getItem(cacheKey);
        return cached ? JSON.parse(cached) : null;
    } catch (e) {
        console.warn('[ProTable] 读取列配置缓存失败:', e);
        return null;
    }
};

/**
 * 将列配置保存到 localStorage
 */
const saveColumnVisibilityToCache = (visibility: Record<string, boolean>) => {
    if (!props.cacheKey) return;

    try {
        const cacheKey = `PRO_TABLE_COLUMNS_${props.cacheKey}`;
        localStorage.setItem(cacheKey, JSON.stringify(visibility));
    } catch (e) {
        console.warn('[ProTable] 保存列配置缓存失败:', e);
    }
};

/**
 * 初始化列配置：读缓存 -> 落地 visible 标记
 */
const initializeColumns = () => {
    const cachedVisibility = loadColumnVisibilityFromCache();

    currentColumns.value = props.columns.map(col => ({
        ...(col as ColumnWithVisibility),
        visible: cachedVisibility?.[col.dataIndex as string] !== false
    }));
};

/**
 * 重置列配置到初始状态（所有列可见）
 */
const resetColumnsToDefault = () => {
    currentColumns.value = props.columns.map(col => ({
        ...(col as ColumnWithVisibility),
        visible: true
    }));

    const visibility: Record<string, boolean> = {};
    props.columns.forEach(col => {
        visibility[col.dataIndex as string] = true;
    });
    saveColumnVisibilityToCache(visibility);
};

/**
 * 处理列可见性更新
 */
const handleColumnVisibilityChange = (checked: (string | number)[]) => {
    currentColumns.value.forEach(col => {
        col.visible = checked.includes(col.dataIndex as string | number);
    });

    // 同步保存到缓存
    const visibility: Record<string, boolean> = {};
    currentColumns.value.forEach(col => {
        visibility[col.dataIndex as string] = col.visible ?? true;
    });
    saveColumnVisibilityToCache(visibility);
};

// ==========================================
// 6. 生命周期钩子
// ==========================================
onMounted(() => {
    // 初始化列配置
    initializeColumns();
    // 组件初次渲染自动执行首次查询取数
    fetchData();
});
</script>

<style scoped>
.rongshiyi-pro-table {
    background: var(--color-bg-2);
    /* 兼容 Arco 暗色模式的基础背景配置 */
    padding: 16px;
    border-radius: 4px;
}

.pro-table-toolbar {
    display: flex;
    justify-content: flex-end;
    margin-bottom: 12px;
    gap: 8px;
}

.pro-table-search {
    margin-bottom: 16px;
}

.search-actions {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    /* 将查询按钮靠右对齐 */
}

.pro-table-setting-panel {
    min-width: 240px;
    max-height: 400px;
    overflow-y: auto;
    padding: 8px 0;
}

.setting-content {
    display: flex;
    flex-direction: column;
    gap: 6px;
    padding: 0 8px;
}

.setting-content :deep(.arco-checkbox) {
    display: flex;
    width: 100%;
    padding: 4px 0;
}

.setting-actions {
    display: flex;
    justify-content: center;
    padding: 0 8px;
}
</style>

// packages/ui-react/src/components/ProTable/index.tsx
import React, { useState, useEffect, useCallback, useMemo } from 'react';
import {
    Table, Space, Button, Form, Row, Col, Input, Select, DatePicker,
    Tooltip, Popover, Checkbox, Empty, Divider, Switch, Image, message, Dropdown
} from 'antd';
import type { TableProps } from 'antd';
import {
    SettingOutlined, CopyOutlined, MoreOutlined,
    QuestionCircleOutlined
} from '@ant-design/icons';
import type { ProTableProps } from './types';

function formatDateByTemplate(value: any, template = 'YYYY-MM-DD') {
    const date = value instanceof Date ? value : new Date(value);
    if (Number.isNaN(date.getTime())) return value;

    const tokenMap: Record<string, string> = {
        YYYY: String(date.getFullYear()),
        MM: String(date.getMonth() + 1).padStart(2, '0'),
        DD: String(date.getDate()).padStart(2, '0'),
        HH: String(date.getHours()).padStart(2, '0'),
        mm: String(date.getMinutes()).padStart(2, '0'),
        ss: String(date.getSeconds()).padStart(2, '0'),
    };

    return template.replace(/YYYY|MM|DD|HH|mm|ss/g, (token) => tokenMap[token]);
}

function setValueByDataIndex(target: any, dataIndex: any, value: any) {
    const path = Array.isArray(dataIndex) ? dataIndex : [dataIndex];
    if (path.length === 0) return target;

    const cloned = Array.isArray(target) ? [...target] : { ...target };
    let cursor = cloned;

    for (let i = 0; i < path.length - 1; i += 1) {
        const key = path[i];
        const next = cursor?.[key];
        cursor[key] = Array.isArray(next) ? [...next] : { ...(next || {}) };
        cursor = cursor[key];
    }

    cursor[path[path.length - 1]] = value;
    return cloned;
}

export function ProTable<RecordType extends object = any>(props: ProTableProps<RecordType>) {
    const {
        columns = [],
        request,
        requestApi,
        rowKey = 'id',
        headerTitle,
        toolBarRender,
        cacheKey,
        showSetting = true,
        ...restTableProps
    } = props;

    const actualRequest = requestApi || request;

    const getRecordKey = useCallback((record: RecordType) => {
        if (typeof rowKey === 'function') {
            return rowKey(record);
        }
        return (record as any)?.[rowKey as string];
    }, [rowKey]);

    // 状态
    const [dataSource, setDataSource] = useState<RecordType[]>([]);
    const [loading, setLoading] = useState<boolean>(false);
    const [pagination, setPagination] = useState({
        current: 1,
        pageSize: 10,
        total: 0,
    });

    // 搜索表单
    const [searchForm] = Form.useForm();
    const searchColumns = useMemo(() => columns.filter(col => col.search), [columns]);

    // 列显隐
    const getInitialVisibility = () => {
        if (cacheKey) {
            try {
                const cached = localStorage.getItem(`PRO_TABLE_COLUMNS_${cacheKey}`);
                if (cached) return JSON.parse(cached);
            } catch (e) {
                console.warn('ProTable load cache failed:', e);
            }
        }
        const initial: Record<string, boolean> = {};
        columns.forEach(col => {
            const key = (col.dataIndex || col.key) as string;
            if (key) {
                initial[key] = col.hideInTable !== true;
            }
        });
        return initial;
    };

    const [columnVisibility, setColumnVisibility] = useState<Record<string, boolean>>(getInitialVisibility());

    const handleVisibilityChange = (checkedValues: any[]) => {
        const newVisibility = { ...columnVisibility };
        columns.forEach(col => {
            const key = (col.dataIndex || col.key) as string;
            if (key) {
                newVisibility[key] = checkedValues.includes(key);
            }
        });
        setColumnVisibility(newVisibility);
        if (cacheKey) {
            localStorage.setItem(`PRO_TABLE_COLUMNS_${cacheKey}`, JSON.stringify(newVisibility));
        }
    };

    const resetColumnsToDefault = () => {
        const initial: Record<string, boolean> = {};
        columns.forEach(col => {
            const key = (col.dataIndex || col.key) as string;
            if (key) {
                initial[key] = true;
            }
        });
        setColumnVisibility(initial);
        if (cacheKey) {
            localStorage.setItem(`PRO_TABLE_COLUMNS_${cacheKey}`, JSON.stringify(initial));
        }
    };

    // 获取数据
    const fetchData = useCallback(
        async (current: number, pageSize: number, searchParams = {}) => {
            if (!actualRequest) return;
            setLoading(true);
            try {
                const payload = { ...searchParams, page: current, pageSize, current };
                const res = await actualRequest(payload);
                if (res) {
                    setDataSource(res.data || []);
                    setPagination(prev => ({
                        ...prev,
                        current,
                        pageSize,
                        total: res.total || 0,
                    }));
                }
            } catch (error) {
                console.error('ProTable request error:', error);
            } finally {
                setLoading(false);
            }
        },
        [actualRequest]
    );

    useEffect(() => {
        fetchData(1, 10, searchForm.getFieldsValue());
    }, [fetchData, searchForm]);

    const handleTableChange: TableProps<RecordType>['onChange'] = (newPagination) => {
        fetchData(newPagination.current || 1, newPagination.pageSize || 10, searchForm.getFieldsValue());
    };

    const onSearch = (values: any) => {
        const searchColumnMap = new Map(
            searchColumns.map((col) => [String(col.dataIndex || col.key), col])
        );

        const formattedValues = { ...values };
        Object.keys(formattedValues).forEach(key => {
            const col = searchColumnMap.get(key);
            const val = formattedValues[key];
            if (col?.valueType === 'date' && val && typeof val.format === 'function') {
                formattedValues[key] = val.format(col.dateFormat || 'YYYY-MM-DD');
            }
        });
        fetchData(1, pagination.pageSize, formattedValues);
    };

    const onReset = () => {
        searchForm.resetFields();
        fetchData(1, pagination.pageSize, {});
    };

    // 处理列配置（附加自定义渲染）
    const processedColumns = useMemo(() => {
        return columns
            .filter(col => {
                const key = (col.dataIndex || col.key) as string;
                if (!key) return true;
                return columnVisibility[key] !== false;
            })
            .map(col => {
                const finalCol = { ...col } as any;

                // 为标题附加提示
                if (col.tooltip) {
                    finalCol.title = (
                        <Space size={4}>
                            {col.title as React.ReactNode}
                            <Tooltip title={col.tooltip}>
                                <QuestionCircleOutlined style={{ color: 'rgba(0,0,0,0.45)', cursor: 'help' }} />
                            </Tooltip>
                        </Space>
                    );
                }

                // 根据 valueType 映射渲染逻辑
                if (!finalCol.render) {
                    finalCol.render = (text: any, record: RecordType, index: number) => {
                        let renderedNode: React.ReactNode = text;

                        switch (col.valueType) {
                            case 'slot':
                                renderedNode = col.renderSlot?.(text, record, index) || text;
                                break;
                            case 'image':
                                {
                                    let srcList: string[] = [];
                                    if (Array.isArray(text)) srcList = text.filter(Boolean);
                                    else if (typeof text === 'string') srcList = [text];

                                    renderedNode = srcList.length > 0 ? (
                                        <Image src={srcList[0]} height={40} preview={{ src: srcList[0] }} />
                                    ) : <span style={{ color: '#999' }}>暂无图片</span>;
                                }
                                break;
                            case 'video':
                                renderedNode = text ? <video src={text} height={40} controls /> : <span style={{ color: '#999' }}>暂无视频</span>;
                                break;
                            case 'html':
                                renderedNode = <span dangerouslySetInnerHTML={{ __html: text || '' }} />;
                                break;
                            case 'date':
                                {
                                    renderedNode = text ? formatDateByTemplate(text, col.dateFormat || 'YYYY-MM-DD') : '-';
                                }
                                break;
                            case 'switch':
                                renderedNode = (
                                    <Switch
                                        checked={text === (col.switchConfig?.activeValue ?? true)}
                                        disabled={col.switchConfig?.disabled?.(record)}
                                        onChange={(checked) => {
                                            const val = checked ? (col.switchConfig?.activeValue ?? true) : (col.switchConfig?.inactiveValue ?? false);
                                            if (col.dataIndex !== undefined) {
                                                const currentRecordKey = getRecordKey(record);
                                                setDataSource((prev) => prev.map((item) => {
                                                    if (getRecordKey(item) !== currentRecordKey) return item;
                                                    return setValueByDataIndex(item, col.dataIndex, val);
                                                }));
                                            }
                                            col.switchConfig?.onChange?.(val, record);
                                        }}
                                        checkedChildren={col.switchConfig?.activeText}
                                        unCheckedChildren={col.switchConfig?.inactiveText}
                                    />
                                );
                                break;
                            case 'enum':
                            case 'select':
                                {
                                    const hit = col.options?.find(opt => opt.value === text);
                                    renderedNode = hit ? hit.label : text;
                                }
                                break;
                            case 'array':
                                renderedNode = Array.isArray(text) ? text.join(', ') : String(text || '');
                                break;
                            case 'link':
                                renderedNode = <a href={text}>{text}</a>;
                                break;
                            case 'operation':
                                if (col.operation) {
                                    const visibleOps = col.operation.slice(0, 3);
                                    const dropOps = col.operation.length > 3 ? col.operation.slice(3) : [];

                                    renderedNode = (
                                        <Space>
                                            {visibleOps.map((btn, i) => (
                                                <Button
                                                    key={i}
                                                    type="link"
                                                    size="small"
                                                    disabled={btn.disabled?.(record)}
                                                    onClick={() => btn.onClick(record)}
                                                    icon={btn.icon}
                                                    style={{ padding: 0 }}
                                                >
                                                    {btn.label}
                                                </Button>
                                            ))}
                                            {dropOps.length > 0 && (
                                                <Dropdown menu={{
                                                    items: dropOps.map((btn, i) => ({
                                                        key: String(i),
                                                        label: (
                                                            <div onClick={() => !btn.disabled?.(record) && btn.onClick(record)}>
                                                                {btn.icon && <span style={{ marginRight: 8 }}>{btn.icon}</span>}
                                                                {btn.label}
                                                            </div>
                                                        ),
                                                        disabled: btn.disabled?.(record),
                                                    }))
                                                }}>
                                                    <Button type="link" size="small" icon={<MoreOutlined />} />
                                                </Dropdown>
                                            )}
                                        </Space>
                                    );
                                }
                                break;
                            default:
                                renderedNode = text;
                        }

                        // 可复制能力增强
                        if (col.copyable && text) {
                            return (
                                <Space>
                                    {renderedNode}
                                    <Tooltip title="复制">
                                        <CopyOutlined
                                            style={{ color: '#1890ff', cursor: 'pointer' }}
                                            onClick={() => {
                                                navigator.clipboard.writeText(String(text));
                                                message.success('复制成功');
                                            }}
                                        />
                                    </Tooltip>
                                </Space>
                            );
                        }
                        return renderedNode;
                    };
                }

                return finalCol;
            });
    }, [columns, columnVisibility]);

    // 渲染列设置勾选项
    const columnOptions = useMemo(() => {
        return columns.map(col => {
            const key = (col.dataIndex || col.key) as string;
            return {
                label: col.title as React.ReactNode,
                value: key,
                disabled: !key
            };
        }).filter(opt => opt.value); // 仅保留带 key/dataIndex 的项
    }, [columns]);

    const checkedColumnValues = useMemo(() => {
        return Object.keys(columnVisibility).filter(k => columnVisibility[k]);
    }, [columnVisibility]);

    return (
        <div
            className="rongshiyi-pro-table"
            style={{
                backgroundColor: '#ffffff',
                padding: '24px',
                borderRadius: '8px',
                boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.05), 0 2px 4px -1px rgba(0, 0, 0, 0.03)',
            }}
        >
            {/* 搜索表单 */}
            {searchColumns.length > 0 && (
                <div className="pro-table-search" style={{ marginBottom: 24, paddingBottom: 24, borderBottom: '1px dashed #f0f0f0' }}>
                    <Form form={searchForm} layout="horizontal" onFinish={onSearch}>
                        <Row gutter={[16, 16]}>
                            {searchColumns.map(col => {
                                const key = (col.dataIndex || col.key) as string;
                                return (
                                    <Col xs={24} sm={12} md={8} lg={6} key={key}>
                                        <Form.Item name={key} label={col.title as React.ReactNode} style={{ marginBottom: 0 }}>
                                            {col.valueType === 'select' || col.valueType === 'enum' ? (
                                                <Select placeholder="请选择" allowClear options={col.options} />
                                            ) : col.valueType === 'date' ? (
                                                <DatePicker style={{ width: '100%' }} allowClear format={col.dateFormat || 'YYYY-MM-DD'} />
                                            ) : (
                                                <Input placeholder="请输入" allowClear />
                                            )}
                                        </Form.Item>
                                    </Col>
                                );
                            })}
                            <Col style={{ flex: 'auto', textAlign: 'right' }}>
                                <Space>
                                    <Button type="primary" htmlType="submit">查询</Button>
                                    <Button onClick={onReset}>重置</Button>
                                </Space>
                            </Col>
                        </Row>
                    </Form>
                </div>
            )}

            {/* 工具栏 */}
            {(headerTitle || toolBarRender || showSetting) && (
                <div
                    className="pro-table-toolbar"
                    style={{
                        display: 'flex',
                        justifyContent: 'space-between',
                        alignItems: 'center',
                        marginBottom: '16px',
                    }}
                >
                    <div style={{ fontSize: '18px', fontWeight: 600, color: '#1f2937' }}>
                        {headerTitle}
                    </div>
                    <Space size="middle">
                        {toolBarRender && toolBarRender().map((item, index) => (
                            <React.Fragment key={index}>{item}</React.Fragment>
                        ))}

                        {showSetting && (
                            <Popover
                                placement="bottomRight"
                                trigger="click"
                                content={
                                    <div style={{ width: 200, maxHeight: 300, overflowY: 'auto' }}>
                                        {columnOptions.length > 0 ? (
                                            <Checkbox.Group
                                                style={{ display: 'flex', flexDirection: 'column', gap: 8 }}
                                                options={columnOptions}
                                                value={checkedColumnValues}
                                                onChange={handleVisibilityChange}
                                            />
                                        ) : (
                                            <Empty description="暂无可配置列" image={Empty.PRESENTED_IMAGE_SIMPLE} />
                                        )}
                                        <Divider style={{ margin: '8px 0' }} />
                                        <div style={{ textAlign: 'center' }}>
                                            <Button type="link" size="small" onClick={resetColumnsToDefault}>重置默认</Button>
                                        </div>
                                    </div>
                                }
                            >
                                <Button icon={<SettingOutlined />} size="middle">列设置</Button>
                            </Popover>
                        )}
                    </Space>
                </div>
            )}

            {/* 表格 */}
            <Table<RecordType>
                rowKey={rowKey}
                columns={processedColumns}
                dataSource={actualRequest ? dataSource : (restTableProps as any).dataSource}
                loading={loading}
                pagination={
                    actualRequest
                        ? {
                            current: pagination.current,
                            pageSize: pagination.pageSize,
                            total: pagination.total,
                            showSizeChanger: true,
                            showQuickJumper: true,
                            showTotal: (total) => `共 ${total} 条`
                        }
                        : false
                }
                onChange={handleTableChange}
                {...restTableProps}
            />
        </div>
    );
}
